### PR TITLE
Better metrics testing

### PR DESCRIPTION
**Pull request by konradzdeb**
# Completed

- I've added data frames to the package and documented via roxygen2. 
- Previous tests are replaced with new tests on those sample data frames

---

Not sure if we want to add more sample data to account for various data formats? My next step would be to write a generic utility function to clean column names, to avoid potentially confusing names like `metric.___` and things on those lines. Not sure if we should some more data sets returned by some other service than `demo.robustperception.io`?

### CODE REVIEW

**Comment by konradzdeb** [comment]
Hi @glenn-m ,

So in terms of the checks that are relying on the `curl` package. I understand you want to get rid of these and replace that using `with_mock` from `testthat`? I think its's a better approach, my question would be shall we do it within this PR or close and start new one? 
https://github.com/glenn-m/promR/blob/369a58d8d3e73da46a13506c49a9476c16b0ede8/tests/testthat/test-metrics-format.R#L26-L38

The other thing would be to focus on #13. I can progress either of those two items (or something else if more urgent), let me know what would you prefer and I will try to commit some time while on the train during the day.

**Comment by glenn-m** [comment]
> Hi @glenn-m ,
> 
> So in terms of the checks that are relying on the `curl` package. I understand you want to get rid of these and replace that using `with_mock` from `testthat`? I think its's a better approach, my question would be shall we do it within this PR or close and start new one?
> 
> [promR/tests/testthat/test-metrics-format.R](https://github.com/glenn-m/promR/blob/369a58d8d3e73da46a13506c49a9476c16b0ede8/tests/testthat/test-metrics-format.R#L26-L38)
> 
> Lines 26 to 38 in [369a58d](/glenn-m/promR/commit/369a58d8d3e73da46a13506c49a9476c16b0ede8)
>  if (requireNamespace(package = "curl", quietly = TRUE)) { 
>    if (curl::has_internet()) { 
>      prom <- 
>        Prometheus$new(host = "http://demo.robustperception.io", port = 9090) 
>      metrics <- 
>        prom$query(query = "go_goroutines") 
>      test_that(desc = "Metric names are correct", 
>                code = expect_named( 
>                  object = metrics, 
>                  expected = c("X__name__", "instance", "job", "timestamp", "value", "port") 
>                )) 
>    } 
>  } 
> 
> The other thing would be to focus on #13. I can progress either of those two items (or something else if more urgent), let me know what would you prefer and I will try to commit some time while on the train during the day.

Let's merge this PR and we'll create a new branch for adding in some preliminary mock tests. 

If you want to work on the mocks or #13 I don't mind, I'm happy to pick up whatever is left over.

**Review by glenn-m — APPROVED** [review]

**Comment by konradzdeb** [comment]
> If you want to work on the mocks or #13 I don't mind, I'm happy to pick up whatever is left over.

Sounds good, I'm happy to start looking at #13. I reckon I'll learn more about Prometheus by doing that. If I get stuck I will post comments under #13, does that sound like a plan?

**Comment by glenn-m** [comment]
@konradzdeb Sure sounds good!

**Pull request merged**
