### PR TITLE
Basic usage vignette

### PR DESCRIPTION
**Pull request by konradzdeb**
Hi, 
I've made some small addition to *basic usage* vignette and wrapped that in `httptest` framework so vignette will compile without host available. I've also refreshed `pkgdown` site with the new content. There is not much to it other than what's in `README` but at least is embedded in the package now.

### CODE REVIEW

**Comment by konradzdeb** [comment]
It's not obvious why it fails on Travis

```
>> devtools::check()
Updating promR documentation
Writing NAMESPACE
Loading promR
Writing NAMESPACE
── Building ─────────────────────────────────────────────────────────────────────────── promR ──
Setting env vars:
● CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
● CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
● CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/Users/huski/Documents/R Projects/promR/DESCRIPTION’ ...
─  preparing ‘promR’: (704ms)
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
✔  creating vignettes (2.2s)
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘promR/.vscode’
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘promR_0.1.1.tar.gz’
   
── Checking ─────────────────────────────────────────────────────────────────────────── promR ──
Setting env vars:
● _R_CHECK_CRAN_INCOMING_USE_ASPELL_: TRUE
● _R_CHECK_CRAN_INCOMING_REMOTE_    : FALSE
● _R_CHECK_CRAN_INCOMING_           : FALSE
● _R_CHECK_FORCE_SUGGESTS_          : FALSE
── R CMD check ─────────────────────────────────────────────────────────────────────────────────
   
   If anything, there should be a Law: Thou Shalt Not Even Think Of Producing A
   Graph That Looks Like Anything From A Spreadsheet.
      -- Ted Harding (in a discussion about producing graphics)
         R-help (August 2007)
   
─  using log directory ‘/private/var/folders/7x/kwc1y_l96t55_rwlv35mg8xh0000gn/T/RtmpNM7fwN/promR.Rcheck’
─  using R version 3.6.1 (2019-07-05)
─  using platform: x86_64-apple-darwin15.6.0 (64-bit)
─  using session charset: UTF-8
─  using options ‘--no-manual --as-cran’
✔  checking for file ‘promR/DESCRIPTION’
─  this is package ‘promR’ version ‘0.1.1’
─  package encoding: UTF-8
✔  checking package namespace information ...
✔  checking package dependencies (3s)
✔  checking if this is a source package
✔  checking if there is a namespace
✔  checking for executable files ...
✔  checking for hidden files and directories
✔  checking for portable file names ...
✔  checking for sufficient/correct file permissions ...
✔  checking serialization versions ...
✔  checking whether package ‘promR’ can be installed (1.3s)
✔  checking installed package size ...
✔  checking package directory ...
✔  checking for future file timestamps (10.2s)
✔  checking ‘build’ directory
✔  checking DESCRIPTION meta-information ...
✔  checking top-level files
✔  checking for left-over files
✔  checking index information ...
✔  checking package subdirectories ...
✔  checking R files for non-ASCII characters ...
✔  checking R files for syntax errors ...
✔  checking whether the package can be loaded ...
✔  checking whether the package can be loaded with stated dependencies ...
✔  checking whether the package can be unloaded cleanly ...
✔  checking whether the namespace can be loaded with stated dependencies ...
✔  checking whether the namespace can be unloaded cleanly ...
✔  checking dependencies in R code ...
✔  checking S3 generic/method consistency (680ms)
✔  checking replacement functions ...
✔  checking foreign function calls ...
✔  checking R code for possible problems (2s)
✔  checking Rd files ...
✔  checking Rd metadata ...
✔  checking Rd line widths ...
✔  checking Rd cross-references ...
✔  checking for missing documentation entries ...
✔  checking for code/documentation mismatches (595ms)
✔  checking Rd \usage sections (871ms)
✔  checking Rd contents ...
✔  checking for unstated dependencies in examples ...
✔  checking contents of ‘data’ directory ...
✔  checking data for non-ASCII characters ...
✔  checking data for ASCII and uncompressed saves ...
✔  checking installed files from ‘inst/doc’ ...
✔  checking files in ‘vignettes’ ...
✔  checking examples (556ms)
   ** found \donttest examples: check also with --run-donttest
✔  checking for unstated dependencies in ‘tests’ ...
─  checking tests ...
✔  Running ‘testthat.R’ (671ms)
✔  checking for unstated dependencies in vignettes (923ms)
✔  checking package vignettes in ‘inst/doc’
✔  checking re-building of vignette outputs (1.1s)
   
   
── R CMD check results ──────────────────────────────────────────────────────── promR 0.1.1 ────
Duration: 25.9s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔
```

**Comment by glenn-m** [comment]
```
--- re-building ‘basic-usage.Rmd’ using rmarkdown

Quitting from lines 45-48 (basic-usage.Rmd) 

Error: processing vignette 'basic-usage.Rmd' failed with diagnostics:

GET http://demo.robustperception.io:9090/api/v1/query?query=go_goroutines&time=1565526357 (demo.robustperception.io-9090/api/v1/query-9d7f3c.json)

--- failed re-building ‘basic-usage.Rmd’

SUMMARY: processing the following file failed:

  ‘basic-usage.Rmd’

Error: Vignette re-building failed.

Execution halted
```

It looks like it's trying to run that GET?

**Comment by konradzdeb** [comment]
That’s what it seems but httptest should take care of that...

--
Konrad

**Comment by konradzdeb** [comment]
I reckon I know why may be a problem. Httptest hashes query string, when that contains asPOSIXct the resulting has differs depending on machine. Deployed on Mac it compiles but not when deployed on Ubuntu. The error points to httptest mechanism not being able to mock the query. I’ll try to re do query strings.

--
Konrad

**Review by glenn-m — APPROVED** [review]
Thanks for solving this, not an easy one! 

What was the issue in the end?

**Comment by konradzdeb** [comment]
It’s a good package and worth working on :) the httptest seems to pose challenges when working with queries that use timestamps as the resulting paths seems to be hashed differently and do not always match. As a side thing, I was thinking of adding automatic pkgdown pages deployment to travis builds. I’ve something like that on a wee SmarterScotland package that I’m working on and it’s a good fun. There is a package called “tic” that facilitates creating configs like that. What do you think?

**Pull request merged**
