### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by konradzdeb**
Logo for the package :) it’s all scripted and easy to modify if needed. Torch image was labelled as for non-commercial reuse.
Source code: https://github.com/konradzdeb/promRlogo

### CODE REVIEW

**Comment by glenn-m** [comment]
I like the idea of the logo, but I think we could find a better torch logo. Maybe something that's a bit wider? Apart from that I think it's great!

**Comment by konradzdeb** [comment]
So I wanted to take Prometheus logo but I think it’s copyrighted, this one was labelled as “free to reuse” but I’ll have a look :)

--
Konrad

**Comment by konradzdeb** [comment]
Found this nice torch icon.

---
*Source: https://github.com/konradzdeb/promRlogo/commit/1c077635f6d36e5aaad0772114141e0e5c202560.*

**Comment by glenn-m** [comment]
Closing this, will have discussion on Logo design and way forward.

**Pull request closed without merging**
